version: "3"

x-app-base: &app-base
  build:
    context: app
  volumes:
    - ./app:/app
    - bundle:/usr/local/bundle

services:
  base:
    <<: *app-base
    command: bundle install

  app:
    <<: *app-base
    command: bundle exec ruby main.rb -o 0.0.0.0
    ports:
      - 4567:4567

volumes:
  bundle:
